/** @type {import('tailwindcss').Config} */
// Tokens ported verbatim from the Stitch exports (DESIGN.md / code.html configs).
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Theme-able tokens reference CSS vars (defined in index.css for dark +
        // light). The rgb(var() / <alpha-value>) form keeps opacity utilities
        // like bg-primary/15 working. Unused Material tokens stay fixed.
        'on-secondary-container': '#fffbff',
        'outline-variant': 'rgb(var(--c-outline-variant) / <alpha-value>)',
        'on-tertiary-fixed': '#001b3e',
        'surface-tint': '#eec065',
        'on-background': '#eae1d7',
        'error-container': '#93000a',
        tertiary: '#aac7ff',
        'on-primary': 'rgb(var(--c-on-primary) / <alpha-value>)',
        'inverse-on-surface': '#343029',
        'on-secondary-fixed': '#241a00',
        primary: 'rgb(var(--c-primary) / <alpha-value>)',
        'on-secondary-fixed-variant': '#584400',
        'secondary-container': '#8f7100',
        'surface-container': 'rgb(var(--c-surface-container) / <alpha-value>)',
        'primary-container': 'rgb(var(--c-primary-container) / <alpha-value>)',
        'on-secondary': '#3d2e00',
        'surface-bright': '#3d3831',
        'text-primary': 'rgb(var(--c-text-primary) / <alpha-value>)',
        error: 'rgb(var(--c-error) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--c-surface-container-lowest) / <alpha-value>)',
        'on-tertiary-fixed-variant': '#22467c',
        background: 'rgb(var(--c-background) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--c-on-primary-container) / <alpha-value>)',
        'tertiary-fixed-dim': '#aac7ff',
        'surface-dim': '#16130d',
        'on-primary-fixed-variant': '#5d4200',
        'on-error-container': '#ffdad6',
        'inverse-primary': '#7b5800',
        'on-surface': 'rgb(var(--c-on-surface) / <alpha-value>)',
        'surface-variant': 'rgb(var(--c-surface-variant) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--c-on-surface-variant) / <alpha-value>)',
        'secondary-fixed': '#ffe08e',
        'surface-container-low': 'rgb(var(--c-surface-container-low) / <alpha-value>)',
        secondary: 'rgb(var(--c-secondary) / <alpha-value>)',
        'surface-container-highest': '#39342d',
        'on-primary-fixed': '#261900',
        'primary-fixed-dim': '#eec065',
        outline: 'rgb(var(--c-outline) / <alpha-value>)',
        'primary-fixed': '#ffdea4',
        'inverse-surface': '#eae1d7',
        'tertiary-fixed': '#d6e3ff',
        'tertiary-container': '#7b9cd7',
        'on-tertiary-container': '#043267',
        'on-error': '#690005',
        'secondary-fixed-dim': '#e9c255',
        'on-tertiary': '#002f64',
        'surface-container-high': 'rgb(var(--c-surface-container-high) / <alpha-value>)',
        surface: 'rgb(var(--c-surface) / <alpha-value>)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        'margin-desktop': '64px',
        'margin-mobile': '16px',
        'container-max': '1440px',
        gutter: '24px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'label-mono': ['JetBrains Mono', 'monospace'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'headline-xl': ['Hanken Grotesk', 'sans-serif'],
        'headline-xl-mobile': ['Hanken Grotesk', 'sans-serif'],
        sans: ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-mono': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['20px', { lineHeight: '30px', fontWeight: '400' }],
        'headline-xl': ['96px', { lineHeight: '100%', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-xl-mobile': ['48px', { lineHeight: '110%', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
