/** @type {import('tailwindcss').Config} */
// Tokens ported verbatim from the Stitch exports (DESIGN.md / code.html configs).
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#fffbff',
        'outline-variant': '#4e4637',
        'on-tertiary-fixed': '#001b3e',
        'surface-tint': '#eec065',
        'on-background': '#eae1d7',
        'error-container': '#93000a',
        tertiary: '#aac7ff',
        'on-primary': '#412d00',
        'inverse-on-surface': '#343029',
        'on-secondary-fixed': '#241a00',
        primary: '#eec065',
        'on-secondary-fixed-variant': '#584400',
        'secondary-container': '#8f7100',
        'surface-container': '#1A1A1A',
        'primary-container': '#bf953f',
        'on-secondary': '#3d2e00',
        'surface-bright': '#3d3831',
        'text-primary': '#FFFFFF',
        error: '#ffb4ab',
        'surface-container-lowest': '#110e08',
        'on-tertiary-fixed-variant': '#22467c',
        background: '#0E0E0E',
        'on-primary-container': '#443000',
        'tertiary-fixed-dim': '#aac7ff',
        'surface-dim': '#16130d',
        'on-primary-fixed-variant': '#5d4200',
        'on-error-container': '#ffdad6',
        'inverse-primary': '#7b5800',
        'on-surface': '#FFFFFF',
        'surface-variant': '#39342d',
        'on-surface-variant': '#d2c5b2',
        'secondary-fixed': '#ffe08e',
        'surface-container-low': '#1f1b15',
        secondary: '#e9c255',
        'surface-container-highest': '#39342d',
        'on-primary-fixed': '#261900',
        'primary-fixed-dim': '#eec065',
        outline: '#3E3E3E',
        'primary-fixed': '#ffdea4',
        'inverse-surface': '#eae1d7',
        'tertiary-fixed': '#d6e3ff',
        'tertiary-container': '#7b9cd7',
        'on-tertiary-container': '#043267',
        'on-error': '#690005',
        'secondary-fixed-dim': '#e9c255',
        'on-tertiary': '#002f64',
        'surface-container-high': '#2e2923',
        surface: '#0E0E0E',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        'margin-desktop': '64px',
        'margin-mobile': '16px',
        'container-max': '1440px',
        gutter: '24px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'label-mono': ['JetBrains Mono', 'monospace'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'headline-xl': ['Hanken Grotesk', 'sans-serif'],
        'headline-xl-mobile': ['Hanken Grotesk', 'sans-serif'],
        sans: ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-mono': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['20px', { lineHeight: '30px', fontWeight: '400' }],
        'headline-xl': ['96px', { lineHeight: '100%', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-xl-mobile': ['48px', { lineHeight: '110%', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
