-- Auto-blog seed: curated blog-lane topics for DisruptorsMedia.
-- Generated from the validated keyword research (blog-lane only; transactional
-- + programmatic keywords are intentionally excluded -> Phase-2 service pages).
-- 45 topics. Idempotent: skips rows whose (client_id, primary_keyword) already exist.

insert into public.blog_queue (client_id, title, primary_keyword, secondary_keywords, cluster, intent, content_type, priority)
select v.* from (values
  ('disruptors-media', 'AI Agents Aren''t Chatbots: What They Actually Do (and Why Your Competitors Are Already Using Them)', 'ai agents', ARRAY['what are ai agents','how do ai agents work','types of ai agents','ai agent examples'], 'AI Agents', 2, 'authority', 1),
  ('disruptors-media', 'What AI Automation Really Is (and the Busywork It Kills in Your First 30 Days)', 'ai automation', ARRAY['what is ai automation','ai automation examples','benefits of ai automation','ai automation vs rpa'], 'Automation', 3, 'authority', 1),
  ('disruptors-media', 'Why "Post More Content" Won''t Fix Your Lead Problem - Here''s What Actually Does', 'how to get more leads for my business', ARRAY['how to get more customers for service business','best way to get leads for contractors','how to grow a service business'], 'Problem-Aware', 3, 'guide', 1),
  ('disruptors-media', 'Generative Engine Optimization: How to Get Your Business Cited by ChatGPT, Not Just Ranked on Google', 'generative engine optimization', ARRAY['ai search optimization','ai seo services'], 'GEO', 3, 'authority', 1),
  ('disruptors-media', 'AI Agents Are Quietly Doing Your Marketing Team''s Busywork. Here''s What That Actually Means.', 'ai agents for marketing', ARRAY['agentic ai','ai agents','ai marketing agents','autonomous marketing'], 'Mktg Automation', 2, 'authority', 1),
  ('disruptors-media', 'What a Fractional CMO Actually Does (and Why Founders Are Skipping the Full-Time Hire)', 'what is a fractional cmo', ARRAY['fractional cmo meaning','fractional chief marketing officer','fractional marketing','fractional marketing director'], 'Fractional', 2, 'informational', 1),
  ('disruptors-media', 'Lead Generation Is Broken for Service Businesses. Here''s the System That Actually Fills Your Pipeline.', 'lead generation', ARRAY['automated lead generation','lead generation for small business','lead generation services for small business'], 'Lead Gen', 3, 'authority', 1),
  ('disruptors-media', 'Agentic AI Is Eating Software: What ''Agentic'' Actually Means, in Plain English', 'agentic ai', ARRAY['what is agentic ai','agentic ai meaning','agentic ai vs generative ai','agentic ai use cases'], 'AI Agents', 2, 'authority', 1),
  ('disruptors-media', 'The 5-Minute Rule: Why Slow Lead Response Is Quietly Killing Your Close Rate', 'how to respond to leads faster', ARRAY['how to stop missing customer calls'], 'Problem-Aware', 3, 'guide', 1),
  ('disruptors-media', 'How to Rank in ChatGPT: The Playbook for Getting Recommended by AI Search', 'how to rank in chatgpt', ARRAY['get found on chatgpt','optimize website for ai search'], 'GEO', 3, 'guide', 1),
  ('disruptors-media', 'AI Marketing Automation Isn''t Hype. It''s the New Baseline for Lean Teams.', 'ai marketing automation', ARRAY['marketing automation','ai marketing','automated marketing','marketing automation software'], 'Mktg Automation', 3, 'authority', 1),
  ('disruptors-media', 'Your Best Salesperson Answers Every Call at 2 AM: What an AI Receptionist Actually Does', 'ai receptionist', ARRAY['ai voice agent','ai phone answering service','conversational ai for business','ai voice assistant for business'], 'Lead Gen', 3, 'authority', 1),
  ('disruptors-media', 'The 6 AI Agents Every Service Business Should Deploy Before the End of the Quarter', 'ai agents for business', ARRAY['ai agents for small business','business ai agent use cases','ai agents for customer service','ai agents for lead generation'], 'AI Agents', 4, 'guide', 1),
  ('disruptors-media', 'GEO vs SEO: Why Ranking #1 on Google Won''t Save You in the AI Search Era', 'geo vs seo', ARRAY['generative engine optimization','ai search optimization'], 'GEO', 2, 'comparison', 1),
  ('disruptors-media', 'The Marketing Automation Tools Worth Paying For in 2026 (and the Ones That''ll Waste Your Budget)', 'best marketing automation software', ARRAY['marketing automation tools','marketing automation platforms','best marketing automation tools','marketing automation software comparison'], 'Mktg Automation', 3, 'comparison', 1),
  ('disruptors-media', 'Automate the Boring 80%: A No-BS Business Automation Playbook for Service Owners', 'business automation', ARRAY['business process automation','how to automate your business','business automation examples','small business automation'], 'Automation', 3, 'guide', 2),
  ('disruptors-media', 'AI Agents vs Automation: Which One Your Business Actually Needs (and When You Need Both)', 'ai agents vs automation', ARRAY['ai agents vs rpa','agentic automation','ai automation vs ai agents','difference between automation and ai agents'], 'AI Agents', 2, 'comparison', 2),
  ('disruptors-media', 'Set It and Forget It: Building a Follow-Up Machine That Books Jobs While You Sleep', 'how to automate follow up', '{}'::text[], 'Problem-Aware', 3, 'guide', 2),
  ('disruptors-media', 'Answer Engine Optimization: The Skill That Decides Whether AI Names You or Your Competitor', 'answer engine optimization', ARRAY['ai search optimization','get found on chatgpt'], 'GEO', 3, 'informational', 2),
  ('disruptors-media', 'How to Automate 80% of Your Social Media Without Sounding Like a Robot', 'social media automation', ARRAY['automate social media posting','social media scheduling','ai social media tools','social media automation tools'], 'Mktg Automation', 2, 'guide', 2),
  ('disruptors-media', 'Fractional CMO vs Full-Time vs Agency: Which One Your Business Actually Needs', 'fractional cmo vs full time', ARRAY['fractional vs in-house cmo','fractional cmo vs agency','part-time cmo','fractional cmo vs marketing agency'], 'Fractional', 3, 'comparison', 2),
  ('disruptors-media', 'Every Missed Call Is a Missed Invoice: How Missed-Call Text-Back Wins Back Lost Jobs', 'missed call text back', ARRAY['missed call automation','missed call text back for contractors','missed call text back for hvac','missed call text back service'], 'Lead Gen', 3, 'guide', 2),
  ('disruptors-media', 'How to Vet a Marketing Agency: The Questions the Pitch Deck Hopes You Never Ask', 'marketing agency', ARRAY['digital marketing agency','marketing consultant','small business marketing services'], 'Agency / Broad', 3, 'comparison', 2),
  ('disruptors-media', 'The Home-Services Lead Machine: How Contractors Book More Jobs Without Buying Shared Leads', 'lead generation for home services', ARRAY['marketing for home services','lead generation for roofers','lead generation for plumbers','hvac lead generation'], 'Vertical', 3, 'guide', 2),
  ('disruptors-media', 'Off-the-Shelf Won''t Cut It: How to Build Custom AI Automations Around Your Actual Workflow', 'custom ai automation for business', ARRAY['ai workflow automation','custom ai workflows','ai automation ideas','how to automate with ai'], 'Automation', 4, 'guide', 2),
  ('disruptors-media', 'Your CRM Is a Gold Mine: How to Reactivate Dead Leads for Almost Nothing', 'how to reactivate old leads', '{}'::text[], 'Problem-Aware', 3, 'guide', 2),
  ('disruptors-media', 'AI Search Optimization for Service Businesses: Show Up When Buyers Ask AI Who to Hire', 'ai search optimization for service business', ARRAY['geo for local business','get found on chatgpt'], 'GEO', 4, 'guide', 2),
  ('disruptors-media', 'The Email Automation Sequences That Actually Nurture Leads (Not Annoy Them)', 'email marketing automation', ARRAY['email automation','drip campaigns','automated email sequences','lead nurturing emails'], 'Mktg Automation', 3, 'guide', 2),
  ('disruptors-media', 'What a Fractional CMO Really Costs in 2026 (and How to Tell If You''re Overpaying)', 'fractional cmo cost', ARRAY['fractional cmo rates','fractional cmo pricing','how much does a fractional cmo cost','fractional cmo salary'], 'Fractional', 3, 'informational', 2),
  ('disruptors-media', 'Kill the Phone Tag: How Automated Booking Fills Your Calendar While You Work', 'automated appointment booking', ARRAY['online booking system for service business','ai appointment booking for service business','appointment setting services'], 'Lead Gen', 3, 'guide', 2),
  ('disruptors-media', 'How to Automate Your Small Business Without Hiring a Single Developer', 'how to automate my small business', ARRAY['how to use ai in my business'], 'Problem-Aware', 3, 'guide', 2),
  ('disruptors-media', 'The Marketing Tasks You Should Never Do Manually Again', 'marketing workflow automation', ARRAY['automate marketing tasks','marketing automation workflows','marketing automation ideas','automated marketing workflows'], 'Mktg Automation', 2, 'guide', 2),
  ('disruptors-media', 'Pay-Per-Lead vs Retainer vs Pay-on-Results: Which Lead-Gen Deal Won''t Torch Your Budget', 'pay per lead agency', ARRAY['performance based lead generation','pay on results lead generation','done for you lead generation'], 'Lead Gen', 4, 'comparison', 2),
  ('disruptors-media', 'Meet the Fractional Chief AI Officer: The Role Every SMB Will Wish It Hired First', 'what is a fractional chief ai officer', ARRAY['do i need a fractional caio'], 'Problem-Aware', 2, 'authority', 2),
  ('disruptors-media', 'How to Vet an AI Automation Agency Before You Hand Over $50K', 'best ai automation agency', ARRAY['best geo agency'], 'Problem-Aware', 4, 'comparison', 2),
  ('disruptors-media', 'Autonomous AI Agents: Separating the 770%-Growth Hype From What Actually Ships Today', 'autonomous ai agents', ARRAY['autonomous ai','autonomous agents examples','self-driving ai agents'], 'AI Agents', 2, 'authority', 3),
  ('disruptors-media', 'How to Get More Google Reviews Without Begging, Bribing, or Breaking the Rules', 'how to get more reviews', '{}'::text[], 'Problem-Aware', 2, 'guide', 3),
  ('disruptors-media', 'GEO for Local Business: Winning the ''Best Service Near Me'' Question Inside ChatGPT and Perplexity', 'geo for local business', ARRAY['optimize website for ai search','geo vs seo'], 'GEO', 4, 'guide', 3),
  ('disruptors-media', 'Turn Your CRM Into a Lead-Closing Machine: A No-Fluff Guide to Automated Follow-Up', 'crm automation', ARRAY['lead nurturing automation','sales automation','automated follow up','crm workflow automation'], 'Mktg Automation', 3, 'guide', 3),
  ('disruptors-media', '5 Signs Your Business Has Outgrown DIY Marketing (and Needs a Fractional CMO)', 'when to hire a fractional cmo', ARRAY['do i need a fractional cmo','signs you need a fractional cmo','fractional cmo for small business'], 'Fractional', 3, 'informational', 3),
  ('disruptors-media', 'HIPAA-Safe Patient Acquisition: How Behavioral Health Practices Fill Caseloads Without Risking Compliance', 'patient acquisition for behavioral health', ARRAY['lead generation for behavioral health','patient acquisition for mental health practices','seo for behavioral health'], 'Vertical', 3, 'authority', 3),
  ('disruptors-media', 'Most Marketing Automation Fails. Here''s the Setup That Doesn''t.', 'does marketing automation work', ARRAY['marketing automation mistakes','why marketing automation fails','marketing automation best practices'], 'Mktg Automation', 2, 'authority', 3),
  ('disruptors-media', 'The Practice Growth Playbook: Turning Clicks Into Booked Chairs for Dental and Med Spas', 'dental practice marketing', ARRAY['lead generation for dentists','med spa lead generation','patient acquisition for med spas','ai receptionist for dental'], 'Vertical', 3, 'guide', 3),
  ('disruptors-media', 'Stop Buying Shared Solar Leads: A Smarter Way to Fill Your Installer Pipeline', 'solar lead generation', ARRAY['lead generation for solar'], 'Vertical', 3, 'guide', 3),
  ('disruptors-media', 'How Law Firms Stop Losing Cases at the Intake Line (With AI That Never Misses a Call)', 'law firm lead generation', ARRAY['ai automation for law firms'], 'Vertical', 3, 'guide', 3)
) as v(client_id, title, primary_keyword, secondary_keywords, cluster, intent, content_type, priority)
where not exists (
  select 1 from public.blog_queue b where b.client_id = v.client_id and b.primary_keyword = v.primary_keyword
);
